before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: cronmutex
    ldflags:
      - -s -w -X github.com/emgag/cronmutex/internal/lib/version.Version={{.Version}} -X github.com/emgag/cronmutex/internal/lib/version.Commit={{.Commit}} -X github.com/emgag/cronmutex/internal/lib/version.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - files:
    - LICENSE
    - README.md
    - cronmutex.yml.dist
